[package]
name = "db-admin"
version = "0.1.0"
edition = "2021"

[dependencies]
hypr-db-core = { workspace = true }
hypr-nango = { path = "../nango", package = "nango" }

async-stripe = { workspace = true, default-features = false, features = ["runtime-tokio-hyper"] }
libsql = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros"] }

schemars = { workspace = true, features = ["chrono"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
strum = { workspace = true, features = ["derive"] }

chrono = { workspace = true, features = ["serde"] }
codes-iso-639 = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
