services:
  caddy:
    image: caddy:2-alpine
    container_name: admin-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    networks:
      - admin-network

  owhisper:
    build:
      context: ./
      dockerfile: ./owhisper/owhisper-server/Dockerfile
    container_name: admin-owhisper
    ports:
      - "8081:8081"
    environment:
      - OWHISPER_PORT=8081
    restart: unless-stopped
    networks:
      - admin-network

  server:
    build:
      context: ./
      dockerfile: ./admin/server/Dockerfile
    container_name: admin-server
    ports:
      - "8082:8082"
    environment:
      - NODE_ENV=production
      - PORT=8082
    restart: unless-stopped
    networks:
      - admin-network

networks:
  admin-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
