[package]
name = "notion"
version = "0.1.0"
edition = "2021"

[dependencies]
hypr-db-user = { workspace = true }

anyhow = { workspace = true }
notion-client = "1.0.5"
strum = { workspace = true, features = ["derive"] }
