[package]
name = "slack"
version = "0.1.0"
edition = "2021"

[dependencies]
hypr-db-user = { workspace = true }

anyhow = { workspace = true }
slack-morphism = { version = "2.9", features = ["axum"] }
url = { workspace = true }
